"""database

Revision ID: 028166c29c94
Revises: 336873c1996b
Create Date: 2023-03-28 13:20:27.271465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028166c29c94'
down_revision = '336873c1996b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
